Feature/events
JbirdL86/math-magicians2 pull request #3
Opened 2021-09-15 21:32 UTC by JbirdL86

What's new :question: 

- Added calculate.js and operate.js under logic folder
- Added constructor to Calculator component
- Added binding method to its constructor

2021-09-15 23:11 UTC, oxenprogrammer requested changes
Hi @JbirdL86 , 

Good job so far!
**To Highlight**
- [x] Professional Repo.
- [x] The Calculator works perfectly. 
I can see you're really putting effort to become a world-class software developer :+1:
There are some issues that you still need to address in order to move forward to the next project.
Trust me you got this! :muscle:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Consider the optional changes nice to have features and only work on them when you have satisfied the required changes_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-15 23:11 UTC, oxenprogrammer commented on src/components/Calculator.js
> +          <button type="button" onClick={this.onClickHandler} className="operation">.</button>
**Changes Required**
- [ ] There is too much repetition of the `button` here making our code not follow the `Don't Repeat Yourself` principle. Let us try to refactor this into a `Button Component` and  pass the name and onClick event as `props`.
- [ ] Let us try to store all the button names in an `array`. In that way, we can then use `array.map` to dynamically add all the buttons into the `Virtual DOM`.

2021-09-15 23:11 UTC, oxenprogrammer commented on src/components/Calculator.js
> +  }
**Changes Required**
- [ ] Every time a button is clicked, the state update will re-render the `virtual DOM`. To handle this in `Class Components`, we need to usually wrap this `side-effect` inside lifecycle methods like `ComponentDidMount` and `ComponentWillUpdate`. Let us try to use lifecycle methods to handle this DOM side effect.

2021-09-16 17:52 UTC, DeliceLydia approved these changes
# Congratulations! 🎉

## Hi @JbirdL86, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 19:13 UTC, merged